### ISSUE TITLE
[DESIGN] Design Home Page, Authentication Workflow & Audit Page

### ISSUE THREAD

**Issue by oyekanmiayo** [BuildForSDG/Team-004-Frontend#5]
Design the following views:

- [x] Home Page detailing general information about the platform and links to registration, login and audit pages @nafiuadegbite 
- [x] Login Pages for SMEs and Investors @samoye01 
- [x] Registration Pages for SMEs and Investors @6lvck @gblessylva 
- [x] Audit Page showing all transactions happening on the platform @idlatest

**Comment by samoye01** [comment]
Done!
